security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        KK\CMSBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:  [in_memory, user_db]
        in_memory:
            memory:
                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: KKCMSBundle:User, property: username }

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /cms/page
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /cms/user, roles: ROLE_ADMIN }
        - { path: /cms/category, roles: ROLE_ADMIN }
        - { path: /cms/page, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }